<a href="https://autonettv.com"><img src="https://assets.autonettv.com/files/logos/logo-trans-rectangle.png" title="AutoNetTV Media, Inc. RelayAPI" class="pull-right"></a>

<h2>Disclaimer</h2>

<p>
    This Drive Marketing plugin is offered as a free tool for subscribing customers of AutoNetTV Media, Inc.’s Drive Marketing to aid their WordPress implementation.
    For more information about AutoNetTV’s video subscription products, please visit www.AutoNetTV.com.
    Users are required to confirm their subscription with AutoNetTV, and to accept the user agreement. AutoNetTV grants to Client a non-transferable, non-exclusive right to access and use such hosted materials during the Term, solely for the benefit of the agreed Client Location(s). Client will not record, copy, download, save, replicate, modify, edit or change any of the AutoNetTV Programs or their content, except as expressly permitted by AutoNetTV in writing. This plugin is provided without any warranty, including any implied warranty of merchantability or fitness for a particular purpose.
    © 2020 AutoNetTV Media, Inc. All rights reserved.
</p>

<h2>Operation</h2>

<p>This plugin uses AutoNetTV's Relay API in order to deliver blog posts to your wordpress site. It requires very little configuration, but it will make changes to your database in order to add your posts. We make these changes as cautiously as possible, but we also  <strong>STRONGLY RECOMMEND YOU BACK UP ANY IMPORTANT INFORMATION IN YOUR DATABASE.</strong></p>
<p>PHP 7.4+ and Wordpress 5.2+ are required for this plugin, however, we recommend you update to the latest stable versions of PHP and Wordpress in order to gain their security patch support.</p>
<p>Once your API key and domain have been supplied to the plugin, it will automatically synchronize your posts. By default, the plugin only collects future posts. If you would like to collect all posts instead, check the box on the start page under the "Retroactive posts" option.</p>

<h2>Installation & Setup</h2>

<ol>
    <li>Collect your API domain and key information from your website admin portal.</li>
    <li>Click <a href="/wp-admin/admin.php?page=autonettv-relay-api">Settings</a> and enter in your domain and api key, then press the "Save Changes" button.</li>
    <li>Click <a href="/wp-admin/admin.php?page=autonettv-relay-api-category-selections">Category Selections</a> to select which categories you would like to enable for your automated import.</li>
    <li>Click <a href="/wp-admin/admin.php?page=autonettv-relay-api-schedule-selections">Article Sync Schedule</a> to set your article sync schedule. If you only receive one article a week, please set that to weekly or daily.</li>
</ol>

<h2>Technical</h2>

<p>This plugin removes jquery from the basic installation of WordPress and may effect your theme. By using this plugin this must be done to play the videos at the current time.</p>

<h2>Troubleshooting</h2>

<p>If you experience problems with this plugin, please contact us through the information on the "Support" menu. </p>
