<h1>Support</h1>
<h3>Logs</h3>
<p>We log information into three places: the general log, the API log and the database log. This information helps us diagnose and solve problems, so we may request it be sent to us. You can simply copy the text from page. </p>
<h3>Phone</h3>
<p>To report issues, please call us at 801-492-9900.</p>
<h3>Email</h3>
<p>If you'd like to email us instead, you can reach us at support@autonettv.com.</p>